### ISSUE TITLE
Need to use some sort of dependency version control

### ISSUE THREAD

**Issue by jonbonazza** [pki-io/pki.io#17]
When I was working with the code for my recent PR, things wouldn't build because gojsonschema changed its interfaces. In my PR, I took the liberty of updating the code to use the new interfaces.

You should look into a more robust dependency management solution such as Goop as 'go get' doesn't support version freezing. Supporting Goop in particular is just a matter of adding a single file to the repo, so it's not very intrusive either. This would allow you to always build using the same versions of your dependencies.

**Comment by thanasisk** [comment]
I will take care of this when I get home - thanks for the heads up!

**Comment by zeroXten** [comment]
hmm, interesting. I was under the impression that go didn't really use the
package version approach. From

http://golang.org/doc/faq#get_version

"Packages intended for public use should try to maintain backwards
compatibility as they evolve. The Go 1 compatibility guidelines are a good
reference here: don't remove exported names, encourage tagged composite
literals, and so on. If different functionality is required, add a new name
instead of changing an old one. If a complete break is required, create a
new package with a new import path."

I remember reading a blog article somewhere that said something similar.
Can't find it though.

**Comment by jonbonazza** [comment]
In a perfect world, yes this would be ideal, however there is no way to guarantee this and, as in the example I provided, backwards compatibility is lost at times. =(

It's unfortunate that Go hadn't considered this, but I believe that I read there will be official solutions in the future. There was no timeframe given, however. Here at the offices, we use Go for a few different projects and we have had the most success with [Goop](https://github.com/nitrous-io/goop). It's extremely easy to setup and even easier to use. The readme in the link provided shows a quick example. =)

If you want, I can create the Goopfile for this project. It will only take a couple seconds. haha

**Comment by zeroXten** [comment]
Looks like we're using Gom for now. Seems to do the job and is very Gemfile-like, so I'm happy :)

Unless there are any objections, we can probably close this ticket.

**Comment by jonbonazza** [comment]
I'm okay with it. :)

**Comment by thanasisk** [comment]
I am fine with this as well - closing the ticket.
